### ISSUE TITLE
No result from request for access token

### ISSUE THREAD

**Issue by alunking** [parkrun/parkrunAPI#10]
Hi, sorry this is a newbie question probably, but I'm just trying to get the basics working with the PHP library so I can make sure I am doing things right!

I have added the parkrunapi.keys file and the parkrunAPI.php which are being loaded fine. I wasn't sure how to write my client ID, though, is it just the number or do I put the "client-" in front of it?

If I put "client-" in front of it, I get a failed response, however when I remove that, my request returns nothing. The PHP I am using is below. The token is not coming out as valid and I'm not sure why! Is there anything I can do to identify my problem?

Many thanks!
Alun

```php
require_once ("../lib/parkrunAPI.php");
$token = new parkrunAPI("/home/<username>/keys/.parkrunapi.keys", "https://api.parkrun.com/", "app");
if (!($token -> isValid())) {
    print "no good";
} else {
    print "we're good";
}
```

**Comment by alunking** [comment]
A quick update, I figure that the correct format is client-<number> for the client ID, as any other format doesn't get any response. 

Another issue looks like the same problem - rleyton said "You're using the wrong one of your two client_id's for that authentication endpoint", so where do I find the two client ids? This might need to be added to the Wiki!
Thanks
--link to similar problem--
https://github.com/parkrun/parkrunAPI/issues/4#issuecomment-63812698

**Comment by adam-cant-run** [comment]
Hi Alun,

Did you ever figure this out? I've tried the Node client and Curl but I get the same problem - no access token. I can confirm that it's an empty response with a client_id starting "client-" and an error with any other format.

Thanks,
Adam

**Comment by alunking** [comment]
Hi Adam, no I didn't unfortunately, I did contact Parkrun (support@parkrun.com) on the 15th December, and was told it was passed to a member of the team, but they didn't get back to me :-(

**Comment by alunking** [comment]
If you get anywhere, let me know!

**Comment by alunking** [comment]
Ah I didn't realise that, but it explains the problems. Good luck!

**Comment by alunking** [comment]
Just had this email regarding my email to support a few months back..

"I'm sorry to inform you that we have decided to put our external API program on hold until further notice.
I apologise that this decision might affect you and your plans however we are in the process of some significant changes and our plans to address this have been delayed.
Should we decide to reintroduce this programme then we will let you know.
Regards
Paul Sinton-Hewitt"

Not sure if this affects access, or just means we'll receive no help for our support! I know of one site regularly using the API so I'll see if I can get in touch with them and find out how they get their token!

**Comment by paulsintonhewitt** [comment]
Hello Alun,
This will affect access. Sorry about that.
