### ISSUE TITLE
Content-Range.EventsRange[0].max varies

### ISSUE THREAD

**Issue by timpoultney** [parkrun/parkrunAPI#6]
Hi, against test-api, a get of /v1/events is behaving a bit counterintuitively.

The response includes: "Content-Range":{"EventsRange":[{"first":0,"last":100,"max":687}]}

Subsequent invocations to fetch the paged data return:
"Content-Range":{"EventsRange":[{"first":100,"last":200,"max":685}]}
"Content-Range":{"EventsRange":[{"first":200,"last":300,"max":685}]}
"Content-Range":{"EventsRange":[{"first":300,"last":400,"max":685}]}
"Content-Range":{"EventsRange":[{"first":400,"last":500,"max":685}]}
"Content-Range":{"EventsRange":[{"first":500,"last":600,"max":685}]}
"Content-Range":{"EventsRange":[{"first":600,"last":685,"max":685}]}

Can you advise what the client behaviour should be here please?

**Comment by timpoultney** [comment]
It's up to 688 today, still returning 685 results.

**Comment by timpoultney** [comment]
geoLocations 683 / 680.

**Comment by FrancesF** [comment]
Hi Tim, thanks for your feedback. There was a caching issue, meaning that results cached in the morning (before the 2 most recent events were added) were returned for the paged data. This has now been fixed.

The value of "first" in the range has also been updated, so it will now show e.g.

first => 1; last => 100; max => 690;
first => 101; last => 200; max => 690;
first => 201; last => 300; max => 690;
first => 301; last => 400; max => 690;
first => 401; last => 500; max => 690;
first => 501; last => 600; max => 690;
first => 601; last => 690; max => 690;

Hopefully this makes it clearer how many items are returned for each page, and that there is no overlap (e.g. might have previously looked like item 100 would appear on the first and second pages, which it didn't). The value of offset to use for fetching the later pages is unchanged.

**Comment by timpoultney** [comment]
Excellent, thanks Frances. I'll update my client code tonight, finish a few unit tests / README and then you can have a pull request containing a Node.js client.
