### ISSUE TITLE
Is the dotnet example in the repository still valid?

### ISSUE THREAD

**Issue by WestDiscGolf** [parkrun/parkrunAPI#7]
Hi,

I've cloned the repository and fired it up in visual studio. It seems to build but when I put a break point on the code behind file and press the button for the basic usage it gets stuck at ...

            Dim someAthletes As ArrayList = parkrunBasicAPIWrapper.APICaller.CallGetService_GetAll( _
                "https://test-api.parkrun.com", "/v1/results/20140408120000", _
                apiToken, userIDForReAuth, userSecretForReAuth, "core", _
                qs, success, tokenWasExpired, callException, newTokenIfReAuthed, expiryIfReAuthed, _
                contentRanges, reAuthorizationException, AddressOf Me.ShowProgressBasicWrapper)

... or when I run the restsharp example I get stuck at ...

            Dim results As List(Of ResultCollection) = _
                parkrunRestSharpAPIWrapper.APICaller.CallGetService_GetAll(Of ResultCollection)( _
                "https://test-api.parkrun.com", "/v1/results/20140409090000", apiToken, _
                userIDForReAuth, userSecretForReAuth, "core", _
                qs, success, tokenWasExpired, callException, newTokenIfReAuthed, expiryIfReAuthed, _
                reAuthorizationException, AddressOf Me.ShowProgressRestSharpWrapper)

Is the authentication in the example not valid any more? Is the example url not valid?

Thanks

**Comment by rleyton** [comment]
Hi there. Sorry for the delay in responding. The code's good, but you'll need to get an access token/credentials to use this. The .NET client library only works with client credentials. Best to get in touch via support.parkrun.com with queries.

If you've set an password to your parkrun profile, you can visit https://www.parkrun.com/profile/developer/ to review/accept the terms, and get a temporary access token, although afraid to say the .NET library may not work without some modification.

**Comment by WestDiscGolf** [comment]
@rleyton Hi, thanks for the update. To be honest I'm a little disappointed about the nature of the openness of the api. There seems to be a lot of red tape around what I was expecting to be a controlled yet restricted (obviously) set of data end points but with wanting people to investigate, play and look to see what people can do with the data like most other web apis (eg. Fitbit, Strava etc.). I originally submitted an application for the api early access program to look into and help write a .net library almost 2 years ago but with limited contact :-(
