### ISSUE TITLE
JSON response to /v1/statistics/events/eventId could be improved

### ISSUE THREAD

**Issue by timpoultney** [parkrun/parkrunAPI#8]
This operation doesn't follow all the others as it returns multiple keys in Content-Range and also has spaces in the key names for the data, e.g.:

```JSON
"Statistics-Records": [
{
"Record Time": "15:01",
"Sex": "M",
"Athlete ID": 111111111,
"Runner": "John AppleSeed",
"Record Date": "12/12/09",
"Event Where Record Set": 12121212,
"Event Run Num Where Record Set": 51,
"Age Grading": 0.85904550499445
},
```

Could this be structured to be more usable in JavaScript please? data["Statistics-Records"][0]["Record Time"] is really cumbersome vs dot notation.

**Comment by rleyton** [comment]
Sorry, suspect it's unlikely statistics elements can be changed in the /v1/ API as used quite heavily in a few places. Might be something that can be reviewed in future. I've created an internal ticket (API-299) and linked it here.
